# Generated by Django 3.2.4 on 2021-06-07 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0002_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
